-- Safety-net spec: verifies that the src.game split loads cleanly and that
-- all public Game.* methods from each sub-module (render, input, controller)
-- and the core (game.lua) are attached and callable.

describe("src.game split load", function()
	local Game

	setup(function()
		Game = require("src.game")
	end)

	-- Core functions (defined in src/game.lua)
	describe("core functions", function()
		it("Game.init is a function", function()
			assert.is_function(Game.init)
		end)
		it("Game.startVsAI is a function", function()
			assert.is_function(Game.startVsAI)
		end)
		it("Game.startTwoPlayer is a function", function()
			assert.is_function(Game.startTwoPlayer)
		end)
		it("Game.startMultiplayer is a function", function()
			assert.is_function(Game.startMultiplayer)
		end)
		it("Game.isMultiplayer is a function", function()
			assert.is_function(Game.isMultiplayer)
		end)
		it("Game.hasMultiplayerSupport is a function", function()
			assert.is_function(Game.hasMultiplayerSupport)
		end)
		it("Game.isVsAI is a function", function()
			assert.is_function(Game.isVsAI)
		end)
		it("Game.getAIDifficulty is a function", function()
			assert.is_function(Game.getAIDifficulty)
		end)
		it("Game.generateTerrain is a function", function()
			assert.is_function(Game.generateTerrain)
		end)
		it("Game.preloadSounds is a function", function()
			assert.is_function(Game.preloadSounds)
		end)
		it("Game.loadSound is a function", function()
			assert.is_function(Game.loadSound)
		end)
		it("Game.playSound is a function", function()
			assert.is_function(Game.playSound)
		end)
		it("Game.playSoundForEvent is a function", function()
			assert.is_function(Game.playSoundForEvent)
		end)
		it("Game.playSoundForPower is a function", function()
			assert.is_function(Game.playSoundForPower)
		end)
		it("Game.syncSoundSettings is a function", function()
			assert.is_function(Game.syncSoundSettings)
		end)
	end)

	-- Render functions (defined in src/game/render.lua)
	describe("render functions", function()
		it("Game.draw is a function", function()
			assert.is_function(Game.draw)
		end)
		it("Game.drawPlayingScreen is a function", function()
			assert.is_function(Game.drawPlayingScreen)
		end)
		it("Game.drawBoard is a function", function()
			assert.is_function(Game.drawBoard)
		end)
		it("Game.drawPieces is a function", function()
			assert.is_function(Game.drawPieces)
		end)
		it("Game.drawUI is a function", function()
			assert.is_function(Game.drawUI)
		end)
		it("Game.drawMenuScreen is a function", function()
			assert.is_function(Game.drawMenuScreen)
		end)
		it("Game.drawSettingsScreen is a function", function()
			assert.is_function(Game.drawSettingsScreen)
		end)
		it("Game.drawGameOverScreen is a function", function()
			assert.is_function(Game.drawGameOverScreen)
		end)
		it("Game.drawPausedScreen is a function", function()
			assert.is_function(Game.drawPausedScreen)
		end)
		it("Game.drawConfirmScreen is a function", function()
			assert.is_function(Game.drawConfirmScreen)
		end)
		it("Game.drawGameModeScreen is a function", function()
			assert.is_function(Game.drawGameModeScreen)
		end)
		it("Game.drawAISelectScreen is a function", function()
			assert.is_function(Game.drawAISelectScreen)
		end)
		it("Game.drawAIIndicator is a function", function()
			assert.is_function(Game.drawAIIndicator)
		end)
		it("Game.drawTurnBanner is a function", function()
			assert.is_function(Game.drawTurnBanner)
		end)
		it("Game.drawAnimations is a function", function()
			assert.is_function(Game.drawAnimations)
		end)
		it("Game.drawParticles is a function", function()
			assert.is_function(Game.drawParticles)
		end)
		it("Game.drawParticleEffect is a function", function()
			assert.is_function(Game.drawParticleEffect)
		end)
		it("Game.drawAnimation is a function", function()
			assert.is_function(Game.drawAnimation)
		end)
		it("Game.drawDestroyRowAnimation is a function", function()
			assert.is_function(Game.drawDestroyRowAnimation)
		end)
		it("Game.drawDestroyColumnAnimation is a function", function()
			assert.is_function(Game.drawDestroyColumnAnimation)
		end)
		it("Game.drawBombAnimation is a function", function()
			assert.is_function(Game.drawBombAnimation)
		end)
		it("Game.drawRelocateAnimation is a function", function()
			assert.is_function(Game.drawRelocateAnimation)
		end)
		it("Game.drawTileHeightAnimation is a function", function()
			assert.is_function(Game.drawTileHeightAnimation)
		end)
		it("Game.drawRecruitAnimation is a function", function()
			assert.is_function(Game.drawRecruitAnimation)
		end)
		it("Game.drawMultiplyAnimation is a function", function()
			assert.is_function(Game.drawMultiplyAnimation)
		end)
		it("Game.drawMoveDiagonalAnimation is a function", function()
			assert.is_function(Game.drawMoveDiagonalAnimation)
		end)
		it("Game.drawJumpProofAnimation is a function", function()
			assert.is_function(Game.drawJumpProofAnimation)
		end)
		it("Game.drawInvisibleAnimation is a function", function()
			assert.is_function(Game.drawInvisibleAnimation)
		end)
		it("Game.drawMoveAgainAnimation is a function", function()
			assert.is_function(Game.drawMoveAgainAnimation)
		end)
		it("Game.drawMPConnectScreen is a function", function()
			assert.is_function(Game.drawMPConnectScreen)
		end)
		it("Game.drawMPLobbyScreen is a function", function()
			assert.is_function(Game.drawMPLobbyScreen)
		end)
		it("Game.drawMPWaitingScreen is a function", function()
			assert.is_function(Game.drawMPWaitingScreen)
		end)
		it("Game.drawInputField is a function", function()
			assert.is_function(Game.drawInputField)
		end)
		it("Game.drawButton is a function", function()
			assert.is_function(Game.drawButton)
		end)
		it("Game.drawMPOpponentScreen is a function", function()
			assert.is_function(Game.drawMPOpponentScreen)
		end)
		it("Game.drawOrbs is a function", function()
			assert.is_function(Game.drawOrbs)
		end)
		it("Game.drawValidMoves is a function", function()
			assert.is_function(Game.drawValidMoves)
		end)
		it("Game.drawPowerTargets is a function", function()
			assert.is_function(Game.drawPowerTargets)
		end)
		it("Game.drawPowerMenu is a function", function()
			assert.is_function(Game.drawPowerMenu)
		end)
		it("Game.drawPowerTooltip is a function", function()
			assert.is_function(Game.drawPowerTooltip)
		end)
		it("Game.drawTileSides is a function", function()
			assert.is_function(Game.drawTileSides)
		end)
		it("Game.drawDestroyedTile is a function", function()
			assert.is_function(Game.drawDestroyedTile)
		end)
		it("Game.drawVolumeBar is a function", function()
			assert.is_function(Game.drawVolumeBar)
		end)
		it("Game.drawCheckbox is a function", function()
			assert.is_function(Game.drawCheckbox)
		end)
	end)

	-- Input functions (defined in src/game/input.lua)
	describe("input functions", function()
		it("Game.mousepressed is a function", function()
			assert.is_function(Game.mousepressed)
		end)
		it("Game.mousereleased is a function", function()
			assert.is_function(Game.mousereleased)
		end)
		it("Game.mousemoved is a function", function()
			assert.is_function(Game.mousemoved)
		end)
		it("Game.keypressed is a function", function()
			assert.is_function(Game.keypressed)
		end)
		it("Game.handleMenuInput is a function", function()
			assert.is_function(Game.handleMenuInput)
		end)
		it("Game.handleGameModeInput is a function", function()
			assert.is_function(Game.handleGameModeInput)
		end)
		it("Game.handleAISelectInput is a function", function()
			assert.is_function(Game.handleAISelectInput)
		end)
		it("Game.handleSettingsInput is a function", function()
			assert.is_function(Game.handleSettingsInput)
		end)
		it("Game.handleGameOverInput is a function", function()
			assert.is_function(Game.handleGameOverInput)
		end)
		it("Game.handlePausedInput is a function", function()
			assert.is_function(Game.handlePausedInput)
		end)
		it("Game.handleConfirmInput is a function", function()
			assert.is_function(Game.handleConfirmInput)
		end)
		it("Game.wheelmoved is a function", function()
			assert.is_function(Game.wheelmoved)
		end)
		it("Game.textinput is a function", function()
			assert.is_function(Game.textinput)
		end)
		it("Game.handleMPConnectInput is a function", function()
			assert.is_function(Game.handleMPConnectInput)
		end)
		it("Game.handleMPLobbyInput is a function", function()
			assert.is_function(Game.handleMPLobbyInput)
		end)
		it("Game.handleMPWaitingInput is a function", function()
			assert.is_function(Game.handleMPWaitingInput)
		end)
		it("Game.handleMPOpponentInput is a function", function()
			assert.is_function(Game.handleMPOpponentInput)
		end)
	end)

	-- Controller functions (defined in src/game/controller.lua)
	describe("controller functions", function()
		it("Game.update is a function", function()
			assert.is_function(Game.update)
		end)
		it("Game.executeAIMove is a function", function()
			assert.is_function(Game.executeAIMove)
		end)
		it("Game.showTurnBanner is a function", function()
			assert.is_function(Game.showTurnBanner)
		end)
		it("Game.startNewGame is a function", function()
			assert.is_function(Game.startNewGame)
		end)
		it("Game.activatePower is a function", function()
			assert.is_function(Game.activatePower)
		end)
		it("Game.getPowerTargets is a function", function()
			assert.is_function(Game.getPowerTargets)
		end)
		it("Game.executepower is a function", function()
			assert.is_function(Game.executepower)
		end)
		it("Game.refreshSelection is a function", function()
			assert.is_function(Game.refreshSelection)
		end)
		it("Game.spawnPowerParticles is a function", function()
			assert.is_function(Game.spawnPowerParticles)
		end)
		it("Game.spawnOrbParticles is a function", function()
			assert.is_function(Game.spawnOrbParticles)
		end)
		it("Game.handlePieceOverheat is a function", function()
			assert.is_function(Game.handlePieceOverheat)
		end)
		it("Game.getMaxPowerCount is a function", function()
			assert.is_function(Game.getMaxPowerCount)
		end)
		it("Game.handleMultiplayerEvent is a function", function()
			assert.is_function(Game.handleMultiplayerEvent)
		end)
		it("Game.applyServerGameState is a function", function()
			assert.is_function(Game.applyServerGameState)
		end)
		it("Game.startMultiplayerAIGame is a function", function()
			assert.is_function(Game.startMultiplayerAIGame)
		end)
	end)
end)
