-- Sound Manager Module Tests
-- Tests for sound management, volume control, and event mapping
-- TDD: Write tests first (RED), then implement (GREEN)

package.path = package.path .. ";./?.lua;./?/init.lua"

describe("SoundManager", function()
	local SoundManager

	setup(function()
		SoundManager = require("src.shared.sound_manager")
	end)

	describe("create", function()
		it("returns manager with default settings", function()
			local mgr = SoundManager.create()
			assert.is_table(mgr)
		end)

		it("has master volume of 1.0", function()
			local mgr = SoundManager.create()
			assert.are.equal(1.0, SoundManager.getMasterVolume(mgr))
		end)

		it("has sfx volume of 1.0", function()
			local mgr = SoundManager.create()
			assert.are.equal(1.0, SoundManager.getSFXVolume(mgr))
		end)

		it("has music volume of 0.5", function()
			local mgr = SoundManager.create()
			assert.are.equal(0.5, SoundManager.getMusicVolume(mgr))
		end)

		it("is not muted by default", function()
			local mgr = SoundManager.create()
			assert.is_false(SoundManager.isMuted(mgr))
		end)
	end)

	describe("volume control", function()
		it("setMasterVolume updates value", function()
			local mgr = SoundManager.create()
			SoundManager.setMasterVolume(mgr, 0.7)
			assert.are.equal(0.7, SoundManager.getMasterVolume(mgr))
		end)

		it("setMasterVolume clamps to 0", function()
			local mgr = SoundManager.create()
			SoundManager.setMasterVolume(mgr, -0.5)
			assert.are.equal(0, SoundManager.getMasterVolume(mgr))
		end)

		it("setMasterVolume clamps to 1", function()
			local mgr = SoundManager.create()
			SoundManager.setMasterVolume(mgr, 1.5)
			assert.are.equal(1, SoundManager.getMasterVolume(mgr))
		end)

		it("setSFXVolume updates value", function()
			local mgr = SoundManager.create()
			SoundManager.setSFXVolume(mgr, 0.8)
			assert.are.equal(0.8, SoundManager.getSFXVolume(mgr))
		end)

		it("setMusicVolume updates value", function()
			local mgr = SoundManager.create()
			SoundManager.setMusicVolume(mgr, 0.3)
			assert.are.equal(0.3, SoundManager.getMusicVolume(mgr))
		end)

		it("getEffectiveVolume combines master and sfx", function()
			local mgr = SoundManager.create()
			SoundManager.setMasterVolume(mgr, 0.5)
			SoundManager.setSFXVolume(mgr, 0.8)
			-- 0.5 * 0.8 = 0.4
			assert.are.equal(0.4, SoundManager.getEffectiveVolume(mgr, "sfx"))
		end)

		it("getEffectiveVolume combines master and music", function()
			local mgr = SoundManager.create()
			SoundManager.setMasterVolume(mgr, 0.5)
			SoundManager.setMusicVolume(mgr, 0.6)
			-- 0.5 * 0.6 = 0.3
			assert.are.equal(0.3, SoundManager.getEffectiveVolume(mgr, "music"))
		end)

		it("getEffectiveVolume returns 0 when muted", function()
			local mgr = SoundManager.create()
			SoundManager.setMuted(mgr, true)
			assert.are.equal(0, SoundManager.getEffectiveVolume(mgr, "sfx"))
			assert.are.equal(0, SoundManager.getEffectiveVolume(mgr, "music"))
		end)

		it("setMuted toggles mute state", function()
			local mgr = SoundManager.create()
			SoundManager.setMuted(mgr, true)
			assert.is_true(SoundManager.isMuted(mgr))
			SoundManager.setMuted(mgr, false)
			assert.is_false(SoundManager.isMuted(mgr))
		end)
	end)

	describe("event mapping", function()
		it("getSoundForEvent returns sound for move", function()
			local sound = SoundManager.getSoundForEvent("move")
			assert.is_string(sound)
			assert.is_true(sound:match("%.ogg$") ~= nil)
		end)

		it("getSoundForEvent returns sound for capture", function()
			local sound = SoundManager.getSoundForEvent("capture")
			assert.is_string(sound)
		end)

		it("getSoundForEvent returns sound for select", function()
			local sound = SoundManager.getSoundForEvent("select")
			assert.is_string(sound)
		end)

		it("getSoundForEvent returns nil for unknown", function()
			local sound = SoundManager.getSoundForEvent("unknown_event")
			assert.is_nil(sound)
		end)

		it("getSoundForPower returns sound for bomb", function()
			local sound = SoundManager.getSoundForPower("bomb")
			assert.is_string(sound)
			assert.is_true(sound:match("explosion") ~= nil)
		end)

		it("getSoundForPower returns sound for relocate", function()
			local sound = SoundManager.getSoundForPower("relocate")
			assert.is_string(sound)
			assert.is_true(sound:match("teleport") ~= nil)
		end)

		it("getSoundForPower returns generic for unknown power", function()
			local sound = SoundManager.getSoundForPower("unknown_power")
			assert.is_string(sound)
			assert.is_true(sound:match("power_activate") ~= nil)
		end)
	end)

	describe("sound queue", function()
		it("queueSound adds to pending list", function()
			local mgr = SoundManager.create()
			SoundManager.queueSound(mgr, "move.ogg")
			local pending = SoundManager.getPendingSounds(mgr)
			assert.are.equal(1, #pending)
			assert.are.equal("move.ogg", pending[1])
		end)

		it("getPendingSounds returns queue", function()
			local mgr = SoundManager.create()
			SoundManager.queueSound(mgr, "move.ogg")
			SoundManager.queueSound(mgr, "capture.ogg")
			local pending = SoundManager.getPendingSounds(mgr)
			assert.are.equal(2, #pending)
		end)

		it("clearPending empties queue", function()
			local mgr = SoundManager.create()
			SoundManager.queueSound(mgr, "move.ogg")
			SoundManager.queueSound(mgr, "capture.ogg")
			SoundManager.clearPending(mgr)
			local pending = SoundManager.getPendingSounds(mgr)
			assert.are.equal(0, #pending)
		end)

		it("multiple queues accumulate", function()
			local mgr = SoundManager.create()
			SoundManager.queueSound(mgr, "a.ogg")
			SoundManager.queueSound(mgr, "b.ogg")
			SoundManager.queueSound(mgr, "c.ogg")
			local pending = SoundManager.getPendingSounds(mgr)
			assert.are.equal(3, #pending)
		end)
	end)
end)
