-- UI State Module Tests
-- Tests for UI state management (menus, settings, tooltips)

package.path = package.path .. ";./?.lua;./?/init.lua"

describe("UI", function()
	local UI

	setup(function()
		UI = require("src.shared.ui")
	end)

	describe("createState", function()
		it("returns initial state with menu screen", function()
			local state = UI.createState()
			assert.are.equal("menu", state.screen)
		end)

		it("has selectedIndex of 1", function()
			local state = UI.createState()
			assert.are.equal(1, state.selectedIndex)
		end)

		it("has nil hoveredPower", function()
			local state = UI.createState()
			assert.is_nil(state.hoveredPower)
		end)

		it("has default volume settings", function()
			local state = UI.createState()
			assert.are.equal(1.0, state.masterVolume)
			assert.are.equal(1.0, state.sfxVolume)
			assert.are.equal(0.5, state.musicVolume)
			assert.is_false(state.muted)
		end)
	end)

	describe("screen management", function()
		it("getScreen returns current screen", function()
			local state = UI.createState()
			assert.are.equal("menu", UI.getScreen(state))
		end)

		it("setScreen changes to valid screen", function()
			local state = UI.createState()
			UI.setScreen(state, "playing")
			assert.are.equal("playing", UI.getScreen(state))
		end)

		it("setScreen accepts all valid screens", function()
			local state = UI.createState()
			local validScreens = { "menu", "playing", "settings", "gameover", "gamemode", "aiselect" }
			for _, screen in ipairs(validScreens) do
				UI.setScreen(state, screen)
				assert.are.equal(screen, UI.getScreen(state))
			end
		end)

		it("setScreen rejects invalid screen names", function()
			local state = UI.createState()
			local result = UI.setScreen(state, "invalid_screen")
			assert.is_false(result)
			assert.are.equal("menu", UI.getScreen(state))
		end)

		it("setScreen resets selectedIndex to 1", function()
			local state = UI.createState()
			state.selectedIndex = 3
			UI.setScreen(state, "settings")
			assert.are.equal(1, state.selectedIndex)
		end)

		it("gamemode is a valid screen", function()
			local state = UI.createState()
			local result = UI.setScreen(state, "gamemode")
			assert.is_true(result)
			assert.are.equal("gamemode", UI.getScreen(state))
		end)

		it("aiselect is a valid screen", function()
			local state = UI.createState()
			local result = UI.setScreen(state, "aiselect")
			assert.is_true(result)
			assert.are.equal("aiselect", UI.getScreen(state))
		end)

		it("setScreen to gamemode resets selectedIndex", function()
			local state = UI.createState()
			state.selectedIndex = 3
			UI.setScreen(state, "gamemode")
			assert.are.equal(1, state.selectedIndex)
		end)

		it("setScreen to aiselect resets selectedIndex", function()
			local state = UI.createState()
			state.selectedIndex = 3
			UI.setScreen(state, "aiselect")
			assert.are.equal(1, state.selectedIndex)
		end)
	end)

	describe("menu navigation", function()
		it("getMenuItems returns items for main menu", function()
			local state = UI.createState()
			local items = UI.getMenuItems(state)
			assert.are.equal(3, #items)
			assert.are.equal("New Game", items[1])
			assert.are.equal("Settings", items[2])
			assert.are.equal("Quit", items[3])
		end)

		it("getMenuItems returns items for settings", function()
			local state = UI.createState()
			UI.setScreen(state, "settings")
			local items = UI.getMenuItems(state)
			assert.are.equal(5, #items)
			assert.are.equal("Master Volume", items[1])
			assert.are.equal("SFX Volume", items[2])
			assert.are.equal("Music Volume", items[3])
			assert.are.equal("Sound Enabled", items[4])
			assert.are.equal("Back", items[5])
		end)

		it("getMenuItems returns items for gameover", function()
			local state = UI.createState()
			UI.setScreen(state, "gameover")
			local items = UI.getMenuItems(state)
			assert.are.equal(2, #items)
			assert.are.equal("Play Again", items[1])
			assert.are.equal("Main Menu", items[2])
		end)

		it("getMenuItems returns empty for playing screen", function()
			local state = UI.createState()
			UI.setScreen(state, "playing")
			local items = UI.getMenuItems(state)
			assert.are.equal(0, #items)
		end)

		it("getMenuItems returns items for gamemode screen", function()
			local state = UI.createState()
			UI.setScreen(state, "gamemode")
			local items = UI.getMenuItems(state)
			assert.are.equal(4, #items)
			assert.are.equal("Local 2-Player", items[1])
			assert.are.equal("VS AI", items[2])
			assert.are.equal("Multiplayer", items[3])
			assert.are.equal("Back", items[4])
		end)

		it("getMenuItems returns items for aiselect screen", function()
			local state = UI.createState()
			UI.setScreen(state, "aiselect")
			local items = UI.getMenuItems(state)
			assert.are.equal(5, #items)
			assert.are.equal("Easy", items[1])
			assert.are.equal("Medium", items[2])
			assert.are.equal("Hard", items[3])
			assert.are.equal("Expert", items[4])
			assert.are.equal("Back", items[5])
		end)

		it("navigation works on gamemode screen", function()
			local state = UI.createState()
			UI.setScreen(state, "gamemode")
			assert.are.equal("Local 2-Player", UI.getSelectedMenuItem(state))
			UI.selectNext(state)
			assert.are.equal("VS AI", UI.getSelectedMenuItem(state))
			UI.selectNext(state)
			assert.are.equal("Multiplayer", UI.getSelectedMenuItem(state))
			UI.selectNext(state)
			assert.are.equal("Back", UI.getSelectedMenuItem(state))
			UI.selectNext(state)
			assert.are.equal("Local 2-Player", UI.getSelectedMenuItem(state)) -- wrap
		end)

		it("navigation works on aiselect screen", function()
			local state = UI.createState()
			UI.setScreen(state, "aiselect")
			assert.are.equal("Easy", UI.getSelectedMenuItem(state))
			UI.selectNext(state)
			assert.are.equal("Medium", UI.getSelectedMenuItem(state))
			UI.selectPrev(state)
			assert.are.equal("Easy", UI.getSelectedMenuItem(state))
			UI.selectPrev(state)
			assert.are.equal("Back", UI.getSelectedMenuItem(state)) -- wrap to end
		end)

		it("selectNext increments selectedIndex", function()
			local state = UI.createState()
			assert.are.equal(1, state.selectedIndex)
			UI.selectNext(state)
			assert.are.equal(2, state.selectedIndex)
		end)

		it("selectNext wraps to 1 at end", function()
			local state = UI.createState()
			state.selectedIndex = 3 -- Last item in main menu
			UI.selectNext(state)
			assert.are.equal(1, state.selectedIndex)
		end)

		it("selectPrev decrements selectedIndex", function()
			local state = UI.createState()
			state.selectedIndex = 2
			UI.selectPrev(state)
			assert.are.equal(1, state.selectedIndex)
		end)

		it("selectPrev wraps to end at 1", function()
			local state = UI.createState()
			state.selectedIndex = 1
			UI.selectPrev(state)
			assert.are.equal(3, state.selectedIndex) -- Wraps to last item
		end)

		it("getSelectedMenuItem returns current item", function()
			local state = UI.createState()
			assert.are.equal("New Game", UI.getSelectedMenuItem(state))
			UI.selectNext(state)
			assert.are.equal("Settings", UI.getSelectedMenuItem(state))
		end)
	end)

	describe("power tooltips", function()
		it("getHoveredPower returns nil initially", function()
			local state = UI.createState()
			assert.is_nil(UI.getHoveredPower(state))
		end)

		it("setHoveredPower stores power info", function()
			local state = UI.createState()
			UI.setHoveredPower(state, "bomb", 100, 200)
			local hovered = UI.getHoveredPower(state)
			assert.is_not_nil(hovered)
			assert.are.equal("bomb", hovered.powerId)
			assert.are.equal(100, hovered.x)
			assert.are.equal(200, hovered.y)
		end)

		it("clearHoveredPower resets to nil", function()
			local state = UI.createState()
			UI.setHoveredPower(state, "bomb", 100, 200)
			UI.clearHoveredPower(state)
			assert.is_nil(UI.getHoveredPower(state))
		end)
	end)

	describe("paused screen", function()
		it("paused is a valid screen", function()
			local state = UI.createState()
			local result = UI.setScreen(state, "paused")
			assert.is_true(result)
			assert.are.equal("paused", UI.getScreen(state))
		end)

		it("paused screen has 4 menu items", function()
			local state = UI.createState()
			UI.setScreen(state, "paused")
			local items = UI.getMenuItems(state)
			assert.are.equal(4, #items)
		end)

		it("paused screen has Continue as first item", function()
			local state = UI.createState()
			UI.setScreen(state, "paused")
			local items = UI.getMenuItems(state)
			assert.are.equal("Continue", items[1])
		end)

		it("paused screen menu items are Continue, New Game, Settings, Quit", function()
			local state = UI.createState()
			UI.setScreen(state, "paused")
			local items = UI.getMenuItems(state)
			assert.are.equal("Continue", items[1])
			assert.are.equal("New Game", items[2])
			assert.are.equal("Settings", items[3])
			assert.are.equal("Quit", items[4])
		end)

		it("navigation works on paused screen", function()
			local state = UI.createState()
			UI.setScreen(state, "paused")
			assert.are.equal("Continue", UI.getSelectedMenuItem(state))
			UI.selectNext(state)
			assert.are.equal("New Game", UI.getSelectedMenuItem(state))
			UI.selectNext(state)
			assert.are.equal("Settings", UI.getSelectedMenuItem(state))
			UI.selectNext(state)
			assert.are.equal("Quit", UI.getSelectedMenuItem(state))
			UI.selectNext(state)
			assert.are.equal("Continue", UI.getSelectedMenuItem(state)) -- wrap
		end)

		it("setScreen to paused resets selectedIndex", function()
			local state = UI.createState()
			state.selectedIndex = 3
			UI.setScreen(state, "paused")
			assert.are.equal(1, state.selectedIndex)
		end)
	end)

	describe("confirm screen", function()
		it("confirm is a valid screen", function()
			local state = UI.createState()
			local result = UI.setScreen(state, "confirm")
			assert.is_true(result)
			assert.are.equal("confirm", UI.getScreen(state))
		end)

		it("confirm screen has 2 menu items", function()
			local state = UI.createState()
			UI.setScreen(state, "confirm")
			local items = UI.getMenuItems(state)
			assert.are.equal(2, #items)
		end)

		it("confirm screen menu items are Yes and No", function()
			local state = UI.createState()
			UI.setScreen(state, "confirm")
			local items = UI.getMenuItems(state)
			assert.are.equal("Yes", items[1])
			assert.are.equal("No", items[2])
		end)

		it("navigation works on confirm screen", function()
			local state = UI.createState()
			UI.setScreen(state, "confirm")
			assert.are.equal("Yes", UI.getSelectedMenuItem(state))
			UI.selectNext(state)
			assert.are.equal("No", UI.getSelectedMenuItem(state))
			UI.selectNext(state)
			assert.are.equal("Yes", UI.getSelectedMenuItem(state)) -- wrap
		end)

		it("setConfirmAction stores action type", function()
			local state = UI.createState()
			UI.setConfirmAction(state, "new_game")
			assert.are.equal("new_game", UI.getConfirmAction(state))
		end)

		it("getConfirmAction returns nil initially", function()
			local state = UI.createState()
			assert.is_nil(UI.getConfirmAction(state))
		end)

		it("clearConfirmAction resets action to nil", function()
			local state = UI.createState()
			UI.setConfirmAction(state, "quit")
			UI.clearConfirmAction(state)
			assert.is_nil(UI.getConfirmAction(state))
		end)
	end)

	describe("volume settings", function()
		it("getMasterVolume returns default 1.0", function()
			local state = UI.createState()
			assert.are.equal(1.0, UI.getMasterVolume(state))
		end)

		it("setMasterVolume updates value", function()
			local state = UI.createState()
			UI.setMasterVolume(state, 0.5)
			assert.are.equal(0.5, UI.getMasterVolume(state))
		end)

		it("setMasterVolume clamps to 0", function()
			local state = UI.createState()
			UI.setMasterVolume(state, -0.5)
			assert.are.equal(0, UI.getMasterVolume(state))
		end)

		it("setMasterVolume clamps to 1", function()
			local state = UI.createState()
			UI.setMasterVolume(state, 1.5)
			assert.are.equal(1, UI.getMasterVolume(state))
		end)

		it("getSFXVolume returns default 1.0", function()
			local state = UI.createState()
			assert.are.equal(1.0, UI.getSFXVolume(state))
		end)

		it("setSFXVolume updates value", function()
			local state = UI.createState()
			UI.setSFXVolume(state, 0.7)
			assert.are.equal(0.7, UI.getSFXVolume(state))
		end)

		it("setSFXVolume clamps to 0-1", function()
			local state = UI.createState()
			UI.setSFXVolume(state, -1)
			assert.are.equal(0, UI.getSFXVolume(state))
			UI.setSFXVolume(state, 2)
			assert.are.equal(1, UI.getSFXVolume(state))
		end)

		it("getMusicVolume returns default 0.5", function()
			local state = UI.createState()
			assert.are.equal(0.5, UI.getMusicVolume(state))
		end)

		it("setMusicVolume updates value", function()
			local state = UI.createState()
			UI.setMusicVolume(state, 0.3)
			assert.are.equal(0.3, UI.getMusicVolume(state))
		end)

		it("setMusicVolume clamps to 0-1", function()
			local state = UI.createState()
			UI.setMusicVolume(state, -0.1)
			assert.are.equal(0, UI.getMusicVolume(state))
			UI.setMusicVolume(state, 1.1)
			assert.are.equal(1, UI.getMusicVolume(state))
		end)

		it("isMuted returns false by default", function()
			local state = UI.createState()
			assert.is_false(UI.isMuted(state))
		end)

		it("setMuted sets mute state", function()
			local state = UI.createState()
			UI.setMuted(state, true)
			assert.is_true(UI.isMuted(state))
			UI.setMuted(state, false)
			assert.is_false(UI.isMuted(state))
		end)

		it("toggleMuted toggles mute state", function()
			local state = UI.createState()
			assert.is_false(UI.isMuted(state))
			UI.toggleMuted(state)
			assert.is_true(UI.isMuted(state))
			UI.toggleMuted(state)
			assert.is_false(UI.isMuted(state))
		end)

		it("adjustVolume changes master volume by delta", function()
			local state = UI.createState()
			UI.adjustVolume(state, "master", -0.1)
			assert.are.equal(0.9, UI.getMasterVolume(state))
			UI.adjustVolume(state, "master", 0.2)
			assert.are.equal(1.0, UI.getMasterVolume(state)) -- Clamped
		end)

		it("adjustVolume changes sfx volume by delta", function()
			local state = UI.createState()
			UI.adjustVolume(state, "sfx", -0.3)
			assert.are.equal(0.7, UI.getSFXVolume(state))
		end)

		it("adjustVolume changes music volume by delta", function()
			local state = UI.createState()
			UI.adjustVolume(state, "music", 0.2)
			assert.are.equal(0.7, UI.getMusicVolume(state))
		end)
	end)

	-- Phase 4: Opponent Selection Screen for AI Practice
	describe("mpopponent screen", function()
		it("mpopponent is a valid screen", function()
			local state = UI.createState()
			local result = UI.setScreen(state, "mpopponent")
			assert.is_true(result)
			assert.are.equal("mpopponent", UI.getScreen(state))
		end)

		it("mpopponent screen has 6 menu items", function()
			local state = UI.createState()
			UI.setScreen(state, "mpopponent")
			local items = UI.getMenuItems(state)
			assert.are.equal(6, #items)
		end)

		it("mpopponent screen has Wait for Player as first item", function()
			local state = UI.createState()
			UI.setScreen(state, "mpopponent")
			local items = UI.getMenuItems(state)
			assert.are.equal("Wait for Player", items[1])
		end)

		it("mpopponent screen has AI Practice difficulties", function()
			local state = UI.createState()
			UI.setScreen(state, "mpopponent")
			local items = UI.getMenuItems(state)
			assert.are.equal("AI Practice - Easy", items[2])
			assert.are.equal("AI Practice - Medium", items[3])
			assert.are.equal("AI Practice - Hard", items[4])
			assert.are.equal("AI Practice - Expert", items[5])
		end)

		it("mpopponent screen has Cancel as last item", function()
			local state = UI.createState()
			UI.setScreen(state, "mpopponent")
			local items = UI.getMenuItems(state)
			assert.are.equal("Cancel", items[6])
		end)

		it("navigation works on mpopponent screen", function()
			local state = UI.createState()
			UI.setScreen(state, "mpopponent")
			assert.are.equal("Wait for Player", UI.getSelectedMenuItem(state))
			UI.selectNext(state)
			assert.are.equal("AI Practice - Easy", UI.getSelectedMenuItem(state))
			UI.selectNext(state)
			assert.are.equal("AI Practice - Medium", UI.getSelectedMenuItem(state))
			UI.selectNext(state)
			UI.selectNext(state)
			UI.selectNext(state)
			assert.are.equal("Cancel", UI.getSelectedMenuItem(state))
			UI.selectNext(state)
			assert.are.equal("Wait for Player", UI.getSelectedMenuItem(state)) -- wrap
		end)
	end)
end)
